In [1]:
import tensorflow as tf

# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Preprocess the data
x_train = x_train / 255.0
x_test = x_test / 255.0

# Convert labels to one-hot encodings
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

# Define the model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=5)

# Evaluate the model on the test data
test_loss, test_accuracy = model.evaluate(x_test, y_test)
print("Test accuracy:", test_accuracy)


2023-02-08 10:26:30.317880: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-08 10:26:30.419190: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-08 10:26:30.421656: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-08 10:26:30.421669: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore 

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2574 - accuracy: 0.9261
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1130 - accuracy: 0.9662
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0780 - accuracy: 0.9768
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0581 - accuracy: 0.9825
Epoch 5/5
313/313 [==============================] - 0s 658us/step - loss: 0.0737 - accuracy: 0.9770
Test accuracy: 0.9769999980926514


In [2]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 0s 611us/step - loss: 0.0737 - accuracy: 0.9770


[0.0736648440361023, 0.9769999980926514]

In [3]:
pred=model.predict(x_test[:10])
print(pred)

1/1 [==============================] - 0s 44ms/step
[[1.37627339e-07 3.72312958e-10 3.71917304e-06 2.48968485e-04
  2.78042121e-11 1.35867619e-08 6.52479936e-12 9.99746561e-01
  1.05157959e-07 5.89977560e-07]
 [2.72229711e-10 2.69533280e-06 9.99995291e-01 1.53059602e-06
  3.98049700e-17 7.19906079e-11 3.14703069e-10 4.54830350e-15
  4.94591347e-07 5.60828826e-16]
 [1.77832044e-06 9.99102354e-01 2.06992539e-04 5.88700959e-06
  6.58342424e-06 1.07048427e-05 2.30176684e-05 1.09765082e-04
  5.32377861e-04 5.81785457e-07]
 [9.99993622e-01 2.64616435e-08 2.04427306e-06 1.66467711e-08
  5.90583547e-08 2.88226829e-08 2.74025774e-06 1.11328836e-06
  4.35285030e-10 3.44171269e-07]
 [7.62992113e-06 8.24788572e-07 1.37546143e-04 2.53025291e-07
  9.94435489e-01 9.33833689e-07 5.74601072e-05 2.74243066e-05
  1.33875319e-05 5.31906914e-03]
 [5.36853477e-08 9.99864578e-01 6.86111036e-07 1.16537628e-07
  1.25833640e-06 1.82916331e-08 2.23325756e-07 1.12171256e-04
  2.08106721e-05 6.86889763e-08]
 [7.21

In [5]:
import numpy as np
p=np.argmax(pred,axis=1)
print(p)

[7 2 1 0 4 1 4 9 5 9]


In [6]:
print(y_test[:10])

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
