In [3]:
import tensorflow as tf 
import numpy as np 
import pandas as pd 
from tensorflow import keras
from sklearn.datasets import load_iris

In [4]:
iris=load_iris()

In [5]:
print(iris)


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [6]:
x=iris.data
y=iris.target
z=iris.target_names
print(x[0])
print(iris.feature_names)

[5.1 3.5 1.4 0.2]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3)

In [8]:
from tensorflow import keras
from keras.models import Sequential
from tensorflow.keras.layers import Dense

model=Sequential()
model.add(Dense(100,input_shape=(4,),activation="relu"))
model.add(Dense(3,activation="softmax"))

2023-03-20 12:12:31.036084: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-03-20 12:12:31.036366: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-03-20 12:12:31.036383: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (IGN-BLR-LP-0412): /proc/driver/nvidia/version does not exist
2023-03-20 12:12:31.037256: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [9]:

model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               500       
                                                                 
 dense_1 (Dense)             (None, 3)                 303       
                                                                 
Total params: 803
Trainable params: 803
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.fit(x_train, y_train, epochs=10)


Epoch 1/10
4/4 [==============================] - 0s 3ms/step - loss: 1.3016 - accuracy: 0.3143
Epoch 2/10
4/4 [==============================] - 0s 1ms/step - loss: 1.1140 - accuracy: 0.4286
Epoch 3/10
4/4 [==============================] - 0s 2ms/step - loss: 0.9968 - accuracy: 0.6762
Epoch 4/10
4/4 [==============================] - 0s 1ms/step - loss: 0.9634 - accuracy: 0.3048
Epoch 5/10
4/4 [==============================] - 0s 2ms/step - loss: 0.9388 - accuracy: 0.3429
Epoch 6/10
4/4 [==============================] - 0s 1ms/step - loss: 0.9102 - accuracy: 0.3905
Epoch 7/10
4/4 [==============================] - 0s 2ms/step - loss: 0.8699 - accuracy: 0.5810
Epoch 8/10
4/4 [==============================] - 0s 1ms/step - loss: 0.8342 - accuracy: 0.7524
Epoch 9/10
4/4 [==============================] - 0s 2ms/step - loss: 0.8012 - accuracy: 0.7524
Epoch 10/10
4/4 [==============================] - 0s 1ms/step - loss: 0.7788 - accuracy: 0.7143


In [12]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 3ms/step - loss: 0.7466 - accuracy: 0.7778


[0.7465574741363525, 0.7777777910232544]

In [13]:
pred=model.predict(x_test[:10])
print(pred)

1/1 [==============================] - 0s 42ms/step
[[0.5542575  0.24500602 0.20073657]
 [0.5887852  0.22267108 0.18854375]
 [0.53325635 0.2547362  0.2120075 ]
 [0.52477115 0.2610544  0.21417457]
 [0.11183406 0.4347127  0.45345312]
 [0.11884991 0.41301423 0.46813586]
 [0.22817741 0.41013312 0.36168948]
 [0.4206222  0.31845814 0.26091963]
 [0.51217633 0.27000877 0.21781492]
 [0.1358304  0.4528431  0.41132647]]


In [14]:
p=np.argmax(pred,axis=1)
print(p)

[0 0 0 0 2 2 1 0 0 1]


In [15]:
print(y_test)

[0 0 0 0 2 2 1 0 0 2 1 1 0 1 0 2 0 0 2 2 2 2 0 1 0 0 2 0 2 0 2 1 1 2 2 2 1
 1 1 2 0 2 1 1 0]


In [16]:
print(y_test[:10])

[0 0 0 0 2 2 1 0 0 2]


In [17]:
print(x_train[:10])
print(y_train[:10])

[[7.9 3.8 6.4 2. ]
 [7.7 3.8 6.7 2.2]
 [5.8 4.  1.2 0.2]
 [5.5 2.4 3.8 1.1]
 [6.4 2.7 5.3 1.9]
 [5.1 3.4 1.5 0.2]
 [5.4 3.4 1.7 0.2]
 [6.7 3.1 4.7 1.5]
 [6.3 2.8 5.1 1.5]
 [6.  3.4 4.5 1.6]]
[2 2 0 1 2 0 0 1 2 1]
